# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorders', '0003_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
