# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorders', '0005_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_generated',
            field=models.BooleanField(default=0),
        ),
    ]
