# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='SecondName',
            new_name='LastName',
        ),
    ]
