# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20180125_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
