# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Member', 'Member'), ('SuperAdmin', 'SuperAdmin')], default='Customer', max_length=100),
        ),
    ]
