# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0006_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='city',
        ),
    ]
