# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productdata_stars'),
        ('user_panel', '0008_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductData'),
        ),
    ]
