# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0009_ratings_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='star',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
