# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0010_auto_20180201_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='product',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
