# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0012_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='not_useful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='useful',
            field=models.IntegerField(default=0),
        ),
    ]
