# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0013_auto_20180202_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
