# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0014_questions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
