# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180129_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
