# Generated by Django 2.0.1 on 2018-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydata',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
