# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180125_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CategoryData')),
            ],
        ),
        migrations.AddField(
            model_name='productdata',
            name='sub_category_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategoryData'),
        ),
    ]
