# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180125_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdata',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='mass',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
        ),
        migrations.AddField(
            model_name='productdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('gms', 'gms'), ('peices', 'peices'), ('packet', 'packet'), ('box', 'box'), ('Lt', 'Lt'), ('ml', 'ml')], default='Kg', max_length=500),
        ),
    ]
