# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180126_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='dicount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
