# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productdata_dicount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='dicount_percentage',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='productdata',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
