# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_review'),
        ('products', '0007_productdata_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='reviews',
        ),
        migrations.AddField(
            model_name='productdata',
            name='reviews',
            field=models.ManyToManyField(to='user_panel.Review'),
        ),
    ]
