# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180128_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='user_panel.Review'),
        ),
    ]
