# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180128_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=50),
        ),
    ]
